/**
 * Prop definitions (ART_BIBLE §5): what each prop *is* — geometry builder id,
 * first tier, variants, flags. Placement rules live with worldgen in
 * content/placement.ts (TASK-122). Index in PROP_DEFS = PropStore.defId.
 */
import { PropFlag } from '../world/prop-store.ts';

export interface PropDef {
  id: string;
  /** Key in geo PROP_GEO. */
  geo: string;
  /** First tier at which it appears (0–3). */
  tier: 0 | 1 | 2 | 3;
  variants: number;
  /** Footprint radius in u (occupancy + contact blob). */
  footprint: number;
  flags: number;
  /** Distance fade (u) for the per-instance dither: [near, far]. Defaults by tier. */
  fade?: [number, number];
}

const { grounded, windy, groundCover, clusterable } = PropFlag;

export const PROP_DEFS: readonly PropDef[] = [
  // vegetation
  {
    id: 'palm',
    geo: 'palm',
    tier: 1,
    variants: 3,
    footprint: 0.6,
    flags: grounded | windy | clusterable,
  },
  {
    id: 'roundTree',
    geo: 'roundTree',
    tier: 1,
    variants: 3,
    footprint: 0.7,
    flags: grounded | windy | clusterable,
  },
  {
    id: 'pine',
    geo: 'pine',
    tier: 1,
    variants: 3,
    footprint: 0.6,
    flags: grounded | windy | clusterable,
  },
  {
    id: 'giantMushroom',
    geo: 'giantMushroom',
    tier: 1,
    variants: 2,
    footprint: 0.8,
    flags: grounded,
  },
  { id: 'bush', geo: 'bush', tier: 2, variants: 2, footprint: 0.6, flags: grounded | windy },
  { id: 'cropRow', geo: 'cropRow', tier: 2, variants: 2, footprint: 1.0, flags: windy },
  { id: 'haybale', geo: 'haybale', tier: 2, variants: 2, footprint: 0.6, flags: grounded },
  { id: 'reeds', geo: 'reeds', tier: 3, variants: 2, footprint: 0.25, flags: windy | groundCover },
  { id: 'lilyPad', geo: 'lilyPad', tier: 3, variants: 2, footprint: 0.35, flags: groundCover },
  {
    id: 'grassTuft',
    geo: 'grassTuft',
    tier: 3,
    variants: 2,
    footprint: 0.15,
    flags: windy | groundCover,
  },
  {
    id: 'flower',
    geo: 'flower',
    tier: 3,
    variants: 2,
    footprint: 0.12,
    flags: windy | groundCover,
  },
  // coastal
  { id: 'rockCluster', geo: 'rockCluster', tier: 1, variants: 3, footprint: 1.2, flags: grounded },
  // T0 cluster proxy (not placed by rules; generated by the batcher from clusterable trees)
  { id: 'treeBlob', geo: 'treeBlob', tier: 0, variants: 3, footprint: 2, flags: 0 },
];

export const PROP_DEF_INDEX: Record<string, number> = Object.fromEntries(
  PROP_DEFS.map((d, i) => [d.id, i]),
);

/** Default per-tier fade distances (u) for dither fades: [near, far]. */
export const TIER_FADE: Record<number, [number, number]> = {
  0: [0, 1e9],
  1: [320, 420],
  2: [120, 160],
  3: [40, 55],
};
